### ISSUE TITLE
Add styles to the Page

### ISSUE THREAD

**Issue by iusamahub** [iusamahub/JavaScript30#1]
I'm working on this challenges Javascript30. I have hosted this website on github pages. What I want is I haven't added any CSS to it. So I want you to design it by yourself any creative ideas welcome. Let's discuss first if you have any doubts.

**Comment by f-shirley** [comment]
Working on adding some styles now!

**Comment by iusamahub** [comment]
I've merged the request but it doesn't look the same on my window.

![image](https://github.com/iusamahub/JavaScript30/assets/71325129/f178898f-5510-4b30-bd26-b020f8c879bf)


What can you do to improve this?

**Comment by f-shirley** [comment]
I tested your page after the merge on firefox, brave, and chrome web browsers and it looks correct on my side. Are you using chrome?
Try clearing your cache, or opening the webpage in an incognito window. If that doesn't work it may be because the identifiers for the elements within the id data are id's and not classes.

**Comment by iusamahub** [comment]
Yeah it's working on incognito.
Thanks for the contribution.

**Comment by f-shirley** [comment]
Glad to hear that, no problem. Thanks for the opportunity
